---
title: "Collab-assignment-4"
author: "Rohan Baghel"
date: '2022-05-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  message = FALSE,  # Change this to FALSE before you submit your assignment
  warning = FALSE,  # Change this to FALSE before you submit your assignment
  error = FALSE,    # Change this to FALSE before you submit your assignment
  out.width = "80%",
  fig.width = 8, 
  fig.height = 6,
  fig.retina = 3)
set.seed(6)
```

```{r}
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
```

```{r read_data}
La_liga_data <- read.csv("data/laliga_player_stats_english.csv")
```

# Section-1 

# Section-2

# Section-3

```{r}
Midfielder_data <- La_liga_data %>%
  filter(Position == "Midfielder") %>%
  select(Team,
         Name,
         Position,
         Shirt.number,
         Minutes.played,
         Games.played,
         Passes,
         Tackles,
         Interceptions,
         Recoveries,
         Clearances,
         Successful.tackles,
         Unssuccessful.tackles,
         Successful.dribbles,
         Unsuccessful.dribbles,
         Shots.on.target,
         Shots,
         Assists,
         Goals.scored,
         Penalties.won,
         Fouls.committed,
         Fouls.suffered,
         Yellow.Cards,
         Second.Yellows,
         Red.Cards,
         Fouls.committed.per.card,
         Penalties.given.away) %>%
  arrange(desc(Assists))
```

```{r}
Top_10_Midfielder_Assists <- Midfielder_data %>%
  select(Team,
         Name,
         Shirt.number,
         Games.played,
         Assists) %>%
  arrange(desc(Assists))
```

```{r}
Top_10_Midfielder_Goals <- Midfielder_data %>%
  select(Team,
         Name,
         Shirt.number,
         Games.played,
         Goals.scored) %>%
  arrange(desc(Goals.scored))
```

```{r}
Attack_performance <- inner_join(Top_10_Midfielder_Goals,Top_10_Midfielder_Assists)[1:10,1:6]

kable(Attack_performance, caption = "Best Attacking Midfielders in La Liga (Statistics)")
```

```{r }
ggplot(Attack_performance,
       aes(x = Games.played)) +
  geom_col(aes( y = Goals.scored, color = "Goals scored")) +
  geom_col(aes( y = Assists, color = "Assists")) +
  facet_wrap(~Name, ncol = 5) +
  theme_classic() +
  xlab("Games Played") +
  ylab("Attack Performance") +
  labs(title = "Best Attacking Midfielders in La Liga")
  
```

```{r}
Top_10_Midfielder_Recoveries <- Midfielder_data %>%
  select(Team,
         Name,
         Shirt.number,
         Games.played,
         Recoveries) %>%
  arrange(desc(Recoveries))

```

```{r}
Top_10_Midfielder_Successful_tackles <- Midfielder_data %>%
  select(Team,
         Name,
         Shirt.number,
         Games.played,
         Successful.tackles) %>%
  arrange(desc(Successful.tackles))
```

```{r}

Defence_Performance <- inner_join(Top_10_Midfielder_Recoveries,Top_10_Midfielder_Successful_tackles)[1:10,1:6]

kable(Defence_Performance, caption = "Best Defensive Midfielders in La Liga (Statistics)")

```

```{r}
ggplot(Defence_Performance,
       aes(x = Games.played)) +
  geom_col(aes(y = Recoveries, color = "Recoveries")) +
  geom_col( aes(y = Successful.tackles, color = "Successful tackles")) +
  facet_wrap(~Name, ncol = 5) +
  theme_classic() +
  xlab("Games Played") +
  ylab("Defence Performance") +
  labs(title = "Best Defensive Midfielders in La Liga ")
```


```{r}
Best_Midfielder <- inner_join(Defence_Performance,Attack_performance)

kable(Best_Midfielder)
```

# Section-4
